### ISSUE TITLE
Add Chrome Extensions

### ISSUE THREAD

**Issue by jzarca01** [getstation/desktop-app-releases#25]
I stumbled upon https://github.com/getstation/repackage-chrome-extension-for-electron/issues/1 which says that this repo was merged

So i was wondering how would I install Chrome extensions in Station ?

**Comment by towfiqi** [comment]
+1

**Comment by kazuf3** [comment]
+1

I'm suffering for epilepsy for years. "Animation policy" Chrome extension helped me for years till I started using Station.

**Comment by MathieuDebit** [comment]
Hi everyone,

Chrome extensions support in Station is a big job and we are actively working on it. We add most requested ones by hand, so unfortulately we don't offer users to add any extension for now. Also, we can't give you an ETA but it's our top priority.

See this community thread for more info: [Why are extensions so hard to implement? What is the technical difficulty exactly?](https://community.getstation.com/t/why-are-extensions-so-hard-to-implement-what-is-the-technical-difficulty-exactly/2741/2)

Feel free to open new posts on https://community.getstation.com if you need anything, this is where we gather all requests and handle bug reports.
I'm closing this issue since this repo is only used for publishing releases.

Thanks 🙏
