### ISSUE TITLE
Restart to update not working on macOS

### ISSUE THREAD

**Issue by directionforward** [getstation/desktop-app-releases#4]
Restart to update doesn't work on macOS – doesn't seem to be able to finish the quit command in order to replace and restart. Sorry I don't have more technical info. Loving the app generally.

**Comment by magne4000** [comment]
Hi @directionforward, thanks for the report.
It has actually been fixed in version `1.0.7`. If you are at a previous version, just Force Quit the app after the update is downloaded, or [download the last version of Station directly](dl.getstation.com).

For any other future issue, you can now use our brand new [Station Community](https://community.getstation.com/) !
