### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by scottwarren** [getstation/desktop-app-releases#8]
I'd love to help out with the documentation by submitting a pull request where I find typos/misspelt words/etc. Is there a repo where I can do that?

**Comment by alexstrat** [comment]
Hello @scottwarren, Station is not (yet?) open-source, so it's not possible to submit PR for now. Could you just post some screenshots here and we'll correct it!
Thanks!!

**Comment by scottwarren** [comment]
no worries:

https://intercom.help/station/general-questions/why-is-station-better-than-a-traditional-web-browser-for-work

Corrected article (haven't edited too much, really just the typos

Classic web browsers like Chrome, Firefox or Safari are fantastic tools but they were designed to perform traditional web browser (read articles, access social media, etc.). Nowadays at work, we mostly use web applications. Station was designed to centralize and provide faster access to all the web applications you use at work (or commonly referred to as Software as a Service).

Station does 4 things better:

1. It doesn't lead you to "tabs paralysis". All your work tools are neatly organized to avoid you ending up with 50+ tabs stacking up on top of each other. Station was designed to keep even the messiest users organized throughout their workday. 
2. It does work faster. Since Station doesn't accumulate unnecessary tabs it also means that it runs faster than a classic browser. Only the apps you really need are loaded when you launch Station and it makes sure to save your memory to avoid slow down or crashes
3. It helps you keep your focus. Station only offers work applications, therefore, it's impossible to be distracted by non-work related topics inside the app. It's your ultimate medium of focus.
4. It gives you much quicker access to all your work tools. Thanks to features like the search or bookmarking, you can easily organize your most important pages and find them in the blink of an eye.

**Comment by alexstrat** [comment]
Thanks, we are correcting it!  





On Mon, Feb 19, 2018 6:26 AM, Scott Warren notifications@github.com  wrote:
no worries:

https://intercom.help/station/general-questions/why-is-station-better-than-a-traditional-web-browser-for-work

Corrected article (haven't edited too much, really just the typos

Classic web browsers like Chrome, Firefox or Safari are fantastic tools but they
were designed to perform traditional web browser (read articles, access social
media, etc.). Nowadays at work, we mostly use web applications. Station was
designed to centralize and provide faster access to all the web applications you
use at work (or commonly referred to as Software as a Service).

Station does 4 things better:

 1. It doesn't lead you to "tabs paralysis". All your work tools are neatly
    organized to avoid you ending up with 50+ tabs stacking up on top of each
    other. Station was designed to keep even the messiest users organized
    throughout their workday.
 2. It does work faster. Since Station doesn't accumulate unnecessary tabs it
    also means that it runs faster than a classic browser. Only the apps you
    really need are loaded when you launch Station and it makes sure to save
    your memory to avoid slow down or crashes
 3. It helps you keep your focus. Station only offers work applications,
    therefore, it's impossible to be distracted by non-work related topics
    inside the app. It's your ultimate medium of focus.
 4. It gives you much quicker access to all your work tools. Thanks to features
    like the search or bookmarking, you can easily organize your most important
    pages and find them in the blink of an eye.
